# Generated by Django 5.2.1 on 2025-05-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
